### ISSUE TITLE
Request: add support for .htaccess in gopher root directory

### ISSUE THREAD

**Issue by tuklusan** [jgoerzen/pygopherd#14]
Allow gopher clients normal unrestricted access
Allow http clients only if a password defined in .htaccess is provided

**Comment by jgoerzen** [comment]
This is a fine idea, but trying to add HTTP server features to pygopherd seems like a difficult ask.  An alternative here would be to run pygopherd on a non-public port for HTTP requests, and use an Apache reverse proxy to send requests to it.
